### PR TITLE
Cloud9: Added dedicated workspace and use symlink to homeassistant config.

### LINKED ISSUE #177: Cloud9 - workspace directory is (possibly) incorrect
When installing Cloud9 using the scripts the default workspace directory is /home/homeassistant
Since ./.homeassistant directory is hidden (starts with a period) it doesn't show in searches made with Ctrl+E in C9

### PR DESCRIPTION
**Pull request by ludeeus**
## Description:
Uses /home/homeassistant/c9workspace as the workspace.
.homeassistant are symlinked to that workspace as `homeassistant`

ctrl+e works for searching.

**Related issue (if applicable):** Fixes #177 

## Checklist (Required):
  - [x] The code change is tested and works locally.
  - [x] The code is compliant with [Contributing guidelines](https://github.com/home-assistant/hassbian-scripts/blob/master/.github/CONTRIBUTING.md)

### If pertinent:
- [x] Script has validation check of the job.
- [x] Created/Updated documentation at `/docs`

### CODE REVIEW

File: package/opt/hassbian/suites/cloud9.sh [hunk 1]
```diff
@@ -29,7 +29,11 @@ sudo -u homeassistant -H /bin/bash << EOF
   printf "Downloading and installing Cloud9 SDK...\\n"
   git clone git://github.com/c9/core.git /opt/c9sdk
   bash /opt/c9sdk/scripts/install-sdk.sh
-  echo '{"projecttree": {"@showhidden": true,"@hiddenFilePattern": ".n*,*c9*,.b*,.p*,.w*,*.db"}}' | tee /home/homeassistant/.c9/user.settings
+  echo '{"projecttree": {"@showhidden": false,"@hiddenFilePattern": ".n*,*c9*,.b*,.p*,.w*,*.db"}}' | tee /home/homeassistant/.c9/user.settings
+  mkdir /home/homeassistant/c9workspace
+  ln -s /home/homeassistant/.homeassistant/ /home/homeassistant/c9workspace
+  ln -s /home/homeassistant/.c9 /home/homeassistant/c9workspace
+  mv /home/homeassistant/.homeassistant /home/homeassistant/homeassistant
```
Comment (Landrash) [inline package/opt/hassbian/suites/cloud9.sh]: This is a terrible idea. Create a symlink instead and both the default and the change will function.
We should always avoid changing defaults since other projects can assume that they are correct.

**Review by Landrash — CHANGES_REQUESTED** [review]

**Comment by ludeeus** [comment]
@Landrash Agreed! That would have been bad!
Looks like I forgot to put in a subdir in the mv command :(

File: package/opt/hassbian/suites/cloud9.sh [hunk 2]
```diff
@@ -29,7 +29,11 @@ sudo -u homeassistant -H /bin/bash << EOF
   printf "Downloading and installing Cloud9 SDK...\\n"
   git clone git://github.com/c9/core.git /opt/c9sdk
   bash /opt/c9sdk/scripts/install-sdk.sh
-  echo '{"projecttree": {"@showhidden": true,"@hiddenFilePattern": ".n*,*c9*,.b*,.p*,.w*,*.db"}}' | tee /home/homeassistant/.c9/user.settings
+  echo '{"projecttree": {"@showhidden": false,"@hiddenFilePattern": ".n*,*c9*,.b*,.p*,.w*,*.db"}}' | tee /home/homeassistant/.c9/user.settings
+  mkdir /home/homeassistant/c9workspace
+  ln -s /home/homeassistant/.homeassistant/ /home/homeassistant/c9workspace
+  ln -s /home/homeassistant/.c9 /home/homeassistant/c9workspace
+  mv /home/homeassistant/c9workspace/.homeassistant /home/homeassistant/c9workspace/homeassistant
```
Comment (Landrash) [inline package/opt/hassbian/suites/cloud9.sh]: This line makes no sense to me?
 The symlink created should be c9workspace and shouldn't contain this directory?

**Review by Landrash — CHANGES_REQUESTED** [review]

**Comment by ludeeus** [comment]
I will find another way for this

**Comment by ludeeus** [comment]
@Landrash does it look better now?
The result is the same.

**Review by Landrash — APPROVED** [review]

**Comment by Landrash** [comment]
Looks good and can be merged after WIP tag is removed.
