### PR TITLE
cloud9: Add npm install to c9 script to make sure all packages are installed.

### LINKED ISSUE #226: Cloud9 Issue
Make sure your running an up to date version of Hassbian before reporting a problem. If not make sure to specify what version and why so we can recreate the issue in question.

You should only file an issue if you found a bug. Feature and enhancement requests should go in #33 that's dedicated for this usage.

Hassbian-config version (hassbian-config -V):
0.11.1
Script/Suite:
sudo hassbian-config install cloud9
Description of problem:
Service will not start after installing.
Expected:

Traceback/log (if applicable):

pi@hassbian:~ $ sudo systemctl status cloud9@homeassistant.service
● cloud9@homeassistant.service - Cloud9
   Loaded: loaded (/etc/systemd/system/cloud9@homeassistant.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-12-05 07:46:02 EST; 1min 7s ago
  Process: 6032 ExecStart=/opt/c9sdk/server.js -l 0.0.0.0 -a : -w /home/homeassistant/c9workspace (code=exited, status=1/FAILURE)
 Main PID: 6032 (code=exited, status=1/FAILURE)

Dec 05 07:46:02 hassbian server.js[6032]:     at Module.require (internal/modules/cjs/loader.js:636:17)
Dec 05 07:46:02 hassbian server.js[6032]:     at require (internal/modules/cjs/helpers.js:20:18)
Dec 05 07:46:02 hassbian server.js[6032]:     at main (/opt/c9sdk/server.js:74:20)
Dec 05 07:46:02 hassbian server.js[6032]:     at Object.<anonymous> (/opt/c9sdk/server.js:55:5)
Dec 05 07:46:02 hassbian server.js[6032]:     at Module._compile (internal/modules/cjs/loader.js:688:30)
Dec 05 07:46:02 hassbian server.js[6032]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
Dec 05 07:46:02 hassbian server.js[6032]:     at Module.load (internal/modules/cjs/loader.js:598:32)
Dec 05 07:46:02 hassbian systemd[1]: cloud9@homeassistant.service: Main process exited, code=exited, status=1/FAILURE
Dec 05 07:46:02 hassbian systemd[1]: cloud9@homeassistant.service: Unit entered failed state.
Dec 05 07:46:02 hassbian systemd[1]: cloud9@homeassistant.service: Failed with result 'exit-code'.

### PR DESCRIPTION
**Pull request by ludeeus**
## Description:

Adds an extra `npm install` to the install script.

**Related issue (if applicable):** Fixes #226 

## Checklist (Required):
  - [x] The code change is tested and works locally.
  - [x] The code is compliant with [Contributing guidelines](https://github.com/home-assistant/hassbian-scripts/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

File: package/opt/hassbian/suites/cloud9.sh [hunk 1]
```diff
@@ -24,6 +24,9 @@ echo "Creating installation directory..."
 mkdir /opt/c9sdk
 chown homeassistant:homeassistant /opt/c9sdk
 
+echo "Installing npm"
+apt install -y npm
```
Comment (Landrash) [inline package/opt/hassbian/suites/cloud9.sh]: Add a check to see if it's installed first like we do with some of the other scripts?

Comment (ludeeus) [reply package/opt/hassbian/suites/cloud9.sh]: Yeah!

It also looks by the issue #226 that the current check is not good enough, it may need a sleep to allow the service to fail.

**Review by Landrash — APPROVED** [review]
